### ISSUE TITLE
custom DEFAULT_SYS_PASS in docker-compose ,but not effect

### ISSUE THREAD

**Issue by guodidi** [MaksymBilenko/docker-oracle-xe-11g#38]
Hi
I'm use win10 OS.
docker version is:
### 1.  docker version
```
Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:57:19 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:59:19 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

### 2. docker-compose version is:
```
docker-compose version 1.14.0, build c7bdf9e3
docker-py version: 2.3.0
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
```
### 3. it is my docker-compose ：
```
version: '3.1'
services: 
 db: 
    image: sath89/oracle-xe-11g:latest
    ports: 
      - 8080:8080
      - 1521:1521
    volumes: 
      - D:/0_docker_home/docker_data/oracle/oracle:/u01/app/oracle
      
    # environment:  cannot use
    #   - DEFAULT_SYS_PASS: 123456
```
and i cannot custom my passwor 123456. can you give me some point , thanks.
