### ISSUE TITLE
ORA-12528, TNS:listener: all appropriate instances are blocking new connections

### ISSUE THREAD

**Issue by Yangyi-miracle** [MaksymBilenko/docker-oracle-xe-11g#48]
Listener refused the connection with the following error:
ORA-12528, TNS:listener: all appropriate instances are blocking new connections

**Comment by claudiocarcaci** [comment]
Same for me when I share a volume on host machine:

```
services:
  ...
  oracledb:
    image: sath89/oracle-xe-11g
    expose:
      - 1521
    ports:
      - 1521:1521
    volumes:
      - /home/claudio/docker-data/oracledb/data:/u01/app/oracle/oradata
```
